export const PET_LIST_REQUEST = 'PET_LIST_REQUEST';
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS';
export const PET_LIST_FAIL = 'PET_LIST_FAIL';

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST';
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS';
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL';
